# Generated by Django 2.1.2 on 2018-12-14 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealizaOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('horainicio', models.TimeField(default=datetime.time(15, 0))),
                ('horafin', models.TimeField()),
                ('modeloascensor', models.CharField(max_length=50)),
                ('fallasdetectadas', models.CharField(max_length=200)),
                ('reparacionesefectuadas', models.CharField(max_length=200)),
                ('cambiopiezas', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
